{ pkgs, ... }:
{
  home.packages =
    with pkgs;
    [
      actionlint
      alejandra
      argc
      autoconf
      autogen
      automake
      bash-language-server
      bat
      beam.packages.erlang_28.elixir_1_18
      beam.packages.erlang_28.erlang
      btop
      cachix
      charm-freeze
      chromedriver
      cmake
      delta
      direnv
      docker
      docker-compose
      eza
      fastfetch
      fd
      figlet
      fswatch
      gawk
      gh
      git
      git-lfs
      google-chrome
      hyperfine
      jq
      just
      lazydocker
      lazygit
      lua-language-server
      lua5_1
      luarocks
      neovim
      neovim-remote
      nil
      nix-direnv
      nixd
      nixfmt
      nodejs
      openssl
      ripgrep
      rust-analyzer
      selenium-server-standalone
      shellcheck
      shfmt
      silicon
      silver-searcher
      sqlite-interactive
      starship
      stylua
      tailwindcss-language-server
      tmux
      tokei
      tree-sitter
      tree-sitter
      vim
      vscode-langservers-extracted
      yaml-language-server
      yarn
      zk
      zsh
    ]
    ++ (
      if pkgs.stdenv.isLinux then
        [
          gcc
          coreutils
          xclip
          unixtools.ifconfig
          inotify-tools
        ]
      else
        [ ]
    );
}
