#!/usr/bin/env bash


echo "==> Installing XCode"
xcode-select --install

set -e

echo "==> Generating an SSH key"

read -r -p "Email: " email

ssh-keygen -t rsa -b 4096 -C \""$email"\"

echo "==> Copying public key to clipboard"
cat ~/.ssh/id_rsa.pub | pbcopy

echo "==> Upload to GitHub now"
read -r -p "Press enter to continue" tmp

echo "==> Starting ssh-agent"
eval "$(ssh-agent -s)"

echo "==> Adding ssh keys to Keychain"

cat << EOF > ~/.ssh/config
Host *
AddKeysToAgent yes
UseKeychain yes
IdentityFile ~/.ssh/id_rsa 
EOF

echo "==> Adding key to agent"
ssh-add -K ~/.ssh/id_rsa

(
cd ~

echo "==> Cloning dotfiles"
git clone git@github.com:mhanberg/.dotfiles.git

cd .dotfiles

echo "==> Running the install script"
./install
)

echo "🍻 Done!"
