#! /usr/bin/env bash

dirname="$(dirname "$0")"

if ! command -v brew >/dev/null; then
  echo "==> Installing Homebrew ..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "==> Install Homebrew dependencies"
brew bundle

update_shell() {
  local shell_path
  shell_path="$(command -v zsh)"

  echo "==> Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells >/dev/null 2>&1; then
    echo "==> Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ]; then
      echo "==> Updating shell to ZSH"
      update_shell
    fi
    ;;
  *)
    echo "==> Updating shell to ZSH"
    update_shell
    ;;
esac

echo "==> Installing a terminfo file for tmux that supports italics"
tic -x "$dirname"/tmux-terminfo.txt
tic -x "$dirname"/tmux-256color.terminfo
tic -x "$dirname"/xterm-256color.terminfo

source ./rcup

echo "==> Installing languages, tmux, and neovim"
for plugin in erlang elixir nodejs ruby neovim tmux; do
  echo "==> Installing asdf plugin: $plugin"

  asdf plugin add "$plugin"
done
(cd "$HOME" && asdf install)

echo "==> Installing neovim-remote"
pip3 install --user neovim-remote

echo "==> You might need to run stuff from this article"
echo "https://stephencharlesweiss.com/zsh-compinit-insecure-directories/"

echo "==> Install extra remaining apps..."
echo " - [] Shush.app (https://mizage.com/shush/)"
echo " - [] Magnet (App Store)"
echo " - [] MenuBar Stats (App Store)"
echo " - [] Things (App Store)"
