search_paths:
  - "~/src"
  - "~/.dotfiles"
  - "~/Library/Mobile Documents/com~apple~CloudDocs/notes"
exclude_path_components:
  - .git
  - .direnv
  - node_modules
  - deps
  - venv
  - target
max_search_depth: 1
session_name_path_components: 2
follow_links: false
workspace_definitions:
  - name: code
    has_any_file:
      - .git

  - name: notes
    has_any_file:
      - .zk
