search_paths:
  - "~/src"
  - "~/.dotfiles"
  - "~/Library/Mobile Documents/com~apple~CloudDocs/notes"
exclude_path_components:
  - .git
  - .direnv
  - node_modules
  - deps
  - venv
  - target
max_search_depth: 1
session_name_path_components: 2
follow_links: false
workspace_definitions:
  - name: code
    default_layout: code
    has_any_file:
      - .git
  - name: notes
    default_layout: notes
    has_any_file:
      - .zk
layouts:
  - name: code
    commands:
      - tmux rename-window editor
      - tmux new-window
      - tmux rename-window shell
      - tmux select-window -t editor
      - tmux send-keys -t 0 'nvim' C-m
  - name: notes
    commands:
      - tmux send-keys -t 0 'notes' C-m
