#!/usr/bin/env zsh

alias aliases="cat ~/.zsh/aliases"
alias blog="cd ~/Development/blog"
alias dev="cd ~/Development"
alias dotfiles="cd ~/.dotfiles"
alias dropbox="cd ~/Dropbox"
alias ea="vim ~/.zsh/aliases"
alias eal="vim ~/.zsh/aliases.local"
alias ef="vim ~/.zsh/funcs"
alias ev="vim ~/.vimrc"
alias ez="vim ~/.zshrc"
alias gbl="git branch -l"
alias home="cd $HOME"
alias journal="dropbox && cd journal"
alias m="mvim ."
alias l1="ls -1"
alias planet="cd ~/Development/planet_ex"
alias sn="mvim -c 'SimplenoteList'"
alias sz="source ~/.zshrc"
alias v="vim ."

source $HOME/.zsh/aliases.local
