#!/usr/bin/env zsh

alias tmux='direnv exec / tmux'
alias ..="cd .."
alias blog="cd ~/Development/blog"
alias brn="cd ~/Dropbox/br/notes && v"
alias dotfiles="tmuxinator start dotfiles"
alias dropbox="cd ~/Dropbox"
alias ea="vim ~/.zsh/aliases"
alias eal="vim ~/.zsh/aliases.local"
alias ef="vim ~/.zsh/funcs"
alias em="mix ecto.migrate"
alias ep="vim ~/.zsh/mah.zsh-theme"
alias ev="vim ~/.vimrc"
alias ez="vim ~/.zshrc"
alias gbl="git --no-pager branch -l"
alias git-trigger-build="git commit --allow-empty -m 'Trigger Build'"
alias gtb="git-trigger-build"
alias hide-desktop="defaults write com.apple.finder CreateDesktop false; killall Finder"
alias home="cd $HOME"
alias jts="cd ~/Development/jekyll-tailwind-starter"
alias l1="ls -1"
alias lib="cd ~/libcasts"
alias m="mvim -g ."
alias mdkir="mkdir"
alias mux="tmuxinator"
alias scratch="tmuxinator start scratch"
alias show-desktop="defaults write com.apple.finder CreateDesktop true; killall Finder"
alias sz="source ~/.zshrc"
alias tree="tree | less"
alias unwrap-last-commit="git reset HEAD~1"
alias v="vim ."
alias vi="vim ."
alias vim="nvim"
alias vr="vimr . --cur-env"
alias rebuild-blog='curl -X POST -d {} https://api.netlify.com/build_hooks/"$NETLIFY_BLOG_ID"'
alias set-git-email-personal='git config user.email "$PERSONAL_EMAIL"'
alias set-git-email-work='git config user.email "$WORK_EMAIL"'
alias lsf='ls | fzf'
alias mxi='mix'
alias stable-nvim='asdf global neovim stable'
alias update-nvim-stable='asdf uninstall neovim stable && asdf install neovim stable'
alias nightly-nvim='asdf global neovim nightly'
alias update-nvim-nightly='asdf uninstall neovim nightly && asdf install neovim nightly'

# docker
alias dc='docker-compose'

# gh aliases

alias ghc='gh repo clone'
alias ghv='gh repo view -w'

# wallaby
alias mtc="WALLABY_DRIVER=chrome mix test"
alias mts="WALLABY_DRIVER=selenium mix test"

source $HOME/.zsh/aliases.local
