#!/usr/bin/env zsh

alias tsr='tailscale serve reset'

alias nublar="ssh mitchell@nublar"
alias wtf='wtfutil'
alias tmux='direnv exec / tmux'
alias mux="tmuxinator"
alias ..="cd .."
alias blog="cd ~/Development/blog"
alias dotfiles="mux start dotfiles --suppress-tmux-version-warning"
alias dropbox="cd ~/Dropbox"
alias ea="vim ~/.zsh/aliases"
alias eal="vim ~/.zsh/aliases.local"
alias ef="vim ~/.zsh/funcs"
alias em="mix ecto.migrate"
alias ev="nvim ~/.vimrc"
alias ez="$EDITOR ~/.zshrc"
alias gbl="git --no-pager branch -l"
alias git-trigger-build="git commit --allow-empty -m 'Trigger Build'"
alias gtb="git-trigger-build"
alias hide-desktop="defaults write com.apple.finder CreateDesktop false; killall Finder"
alias home="cd $HOME"
alias jts="cd ~/Development/jekyll-tailwind-starter"
alias l1="ls -1"
alias lib="cd ~/libcasts"
alias m="mvim -g ."
alias mdkir="mkdir"
alias scratch="mux start scratch --suppress-tmux-version-warning"
alias show-desktop="defaults write com.apple.finder CreateDesktop true; killall Finder"
alias sz="source ~/.zshrc"
alias tree="tree | less"
alias unwrap-last-commit="git reset HEAD~1"
alias v="vim ."
alias vi="vim ."
alias vim="nvim"
alias vr="vimr . --cur-env"
alias rebuild-blog='curl -X POST -d {} https://api.netlify.com/build_hooks/"$NETLIFY_BLOG_ID"'
alias set-git-email-personal='git config user.email "$PERSONAL_EMAIL"'
alias set-git-email-work='git config user.email "$WORK_EMAIL"'
alias lsf='ls | fzf-tmux -p -- --reverse'
alias mxi='mix'
alias localnvim="/Users/mitchell/localnvim/bin/nvim"
alias shfmt="shfmt -i 2"
alias ls="exa"

alias wave="colorscheme wave kanagawa-wave kanagawa_wave"
alias dragon="colorscheme dragon kanagawa-dragon kanagawa_dragon"

alias dadbod="nvim -c ':DBUI'"

# docker
alias dc='docker-compose'
alias docker-image-remove='docker image rm $(docker image ls -q) --force'

# gh aliases


alias ghc='gh repo clone'
alias ghv='gh repo view -w'
open-pr() {
  pr="$(gh pr list | fzf | awk '{ print $1 }')"

  echo "$pr"

  [[ -z $pr ]] && gh pr view -w "$pr"
}

alias redo-labels='gh pr edit --remove-label elixir --remove-label freeroll && gh pr edit --add-label elixir --add-label freeroll'

# wallaby
alias mtc="WALLABY_DRIVER=chrome mix test"
alias mts="WALLABY_DRIVER=selenium mix test"

## elixir

function mt() {
  if [ -z $1 ]; then
    mix test \
      && terminal-notifier -title "mix test" -subtitle "Test Suite" -message "Success!" \
      || terminal-notifier -title "mix test" -subtitle "Test Suite" -message "Failure!"
  else
    mix test "$1" \
      && terminal-notifier -title "mix test" -subtitle "$1" -message "Success!" \
      || terminal-notifier -title "mix test" -subtitle "$1" -message "Failure!"
  fi
}

function mix-test-watch() {
  fswatch -o . | mix test --stale --listen-on-stdin
}

alias mtw="mix-test-watch"

# tt
standup() {
  echo '[todo]\n[work]\n[review]\n[meeting]\n[other]' | \
    fzf-tmux -p 90% -- --preview-window=down:80% --reverse --disabled --preview='echo "$(tt review)" | rg --fixed-strings {}';
}
ttr() { tt "[review] $1"; }
ttw() { tt "[work] $1"; }
ttm() { tt "[meeting] $1"; }
tto() { tt "[other] $1"; }
ttt() { tt "[todo] $1"; }

alias nvim-plugins="cd ~/.local/share/nvim/site/pack/packer/start"

alias icloud="cd $HOME/Library/Mobile\ Documents/com~apple~CloudDocs"

# zk

alias notes="zk edit --match=README --tag=startup"

source $HOME/.zsh/aliases.local
