#!/usr/bin/env zsh

ga() { git add "$@"; }
gc() { git commit "$@"; }
gcb() { git checkout -b "$@"; }
gco() { git checkout "$@"; }
gcm() { git checkout master; }
gl() { git log --graph "$@"; }
gpull() { git pull "$@"; }
gpush() { git push "$@"; }
gd() { git diff "$@"; }
gs() { git status "$@"; }

aliases() {
  if [ -f ~/.zsh/aliases ]; then
    cat ~/.zsh/aliases
  fi

  if [ -f ~/.zsh/aliases.local ]; then
    cat ~/.zsh/aliases.local
  fi
}
