[colors]

foreground = "#DCD7BA"
background = "#1F1F28"
cursor_bg = "#C8C093"
cursor_border = "#e6e0c2"
cursor_fg = "#1f1f28"
selection_bg = "#2D4F67"
selection_fg = "#C8C093"

ansi = ["#16161D", "#C34043", "#76946A", "#C0A36E", "#7E9CD8", "#957FB8", "#6A9589", "#C8C093"]
brights = ["#727169", "#E82424", "#98BB6C", "#E6C384", "#7FB4CA", "#938AA9", "#7AA89F", "#DCD7BA"]
