name: Build and cache

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main

jobs:
  build-hm:
    strategy:
      matrix:
        include:
          - {host: "mitchell@nublar", os: "ubuntu-latest"}
          - {host: "m.hanberg", os: "macos-latest"}
          - {host: "mitchell@mitchells-mini", os: "macos-latest"}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://mhanberg.cachix.org
            extra-trusted-public-keys = mhanberg.cachix.org-1:tpHVw70kbGnO5mGv4rA3pjxpqeEiP/vWfJT4tVaK85o=
            accept-flake-config = true
      - uses: cachix/cachix-action@v16
        with:
          name: mhanberg
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          useDaemon: false
          cachixArgs: "--verbose"
      - run: nix run home-manager/master -- build --flake ".#${{ matrix.host }}"

  nix-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        host:
          - "mhanberg-GQJNV7J4QY"
          - "mitchells-mini"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://mhanberg.cachix.org
            extra-trusted-public-keys = mhanberg.cachix.org-1:tpHVw70kbGnO5mGv4rA3pjxpqeEiP/vWfJT4tVaK85o=
      - uses: cachix/cachix-action@v16
        with:
          name: mhanberg
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          useDaemon: false
          cachixArgs: "--verbose"
      - run: sudo nix run nix-darwin -- build --flake ".#${{ matrix.host }}"
