name: Build and cache

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main

permissions: {}

jobs:
  build-hm:
    strategy:
      matrix:
        include:
          - { host: "mitchell@nublar", os: "ubuntu-latest" }
          - { host: "mhanberg@Mitchells-MacBook-Pro", os: "macos-latest" }
          - { host: "mitchell@mitchells-mini", os: "macos-latest" }
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup SSH key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          extra_nix_config: |
            extra-substituters = https://mhanberg.cachix.org
            extra-trusted-public-keys = mhanberg.cachix.org-1:tpHVw70kbGnO5mGv4rA3pjxpqeEiP/vWfJT4tVaK85o=
            accept-flake-config = true
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: mhanberg
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          useDaemon: false
          cachixArgs: "--verbose"
      - run: nix run home-manager/master -- build --flake ".#${{ matrix.host }}"

  nix-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        host:
          - "Mitchells-MacBook-Pro"
          - "mitchells-mini"
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup SSH key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          extra_nix_config: |
            extra-substituters = https://mhanberg.cachix.org
            extra-trusted-public-keys = mhanberg.cachix.org-1:tpHVw70kbGnO5mGv4rA3pjxpqeEiP/vWfJT4tVaK85o=
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: mhanberg
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          useDaemon: false
          cachixArgs: "--verbose"
      - run: sudo nix run nix-darwin -- build --flake ".#${{ matrix.host }}"
