name: Build and cache

on:
  push:
    branches:
      - main

jobs:
  build-hm:
    strategy:
      matrix:
        include:
          - {host: "mitchell@nublar", os: "ubuntu-latest"}
          - {host: "m.hanberg", os: "macos-latest"}
          - {host: "mitchell@mitchells-mini", os: "macos-latest"}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: mhanberg
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix run home-manager/master -- build --flake ".#${{ matrix.host }}"

  nix-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        host:
          - "mhanberg-GQJNV7J4QY"
          - "mitchells-mini"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: mhanberg
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: sudo nix run nix-darwin -- build --flake ".#${{ matrix.host }}"
